export const ROLE_DASHBOARDS = {
  customer: {
    path: '/dashboard',
    title: 'Customer Portal',
    subtitle: 'Your stays, invoices & preferences',
    roles: ['customer'],
    links: [
      { to: '/dashboard', label: 'Overview', end: true },
      { to: '/dashboard/profile', label: 'Profile' },
      { to: '/dashboard/bookings', label: 'My Bookings' },
      { to: '/dashboard/invoices', label: 'Invoices' },
      { to: '/dashboard/payments', label: 'Payment History' },
      { to: '/dashboard/reviews', label: 'Reviews' },
      { to: '/dashboard/favorites', label: 'Favorites' },
      { to: '/dashboard/notifications', label: 'Notifications' },
      { to: '/dashboard/assistant', label: 'AI Assistant' },
    ],
  },
  receptionist: {
    path: '/reception',
    title: 'Reception Desk',
    subtitle: 'Front office & guest operations',
    roles: ['receptionist'],
    links: [
      { to: '/reception', label: 'Overview', end: true },
      { to: '/reception/reservations', label: 'Reservations' },
      { to: '/reception/checkin', label: 'Check-in / Check-out' },
      { to: '/reception/rooms', label: 'Room Assignment' },
      { to: '/reception/walkin', label: 'Walk-in Guests' },
      { to: '/reception/guests', label: 'Guest History' },
      { to: '/reception/invoices', label: 'Invoices' },
      { to: '/reception/occupancy', label: 'Occupancy' },
      { to: '/reception/agent-requests', label: 'AI Agent Requests' },
      { to: '/reception/notifications', label: 'Notifications' },
    ],
  },
  restaurant_manager: {
    path: '/restaurant-desk',
    title: 'Restaurant Manager',
    subtitle: 'Menu, dining & kitchen operations',
    roles: ['restaurant_manager'],
    links: [
      { to: '/restaurant-desk', label: 'Overview', end: true },
      { to: '/restaurant-desk/menu', label: 'Restaurant Menu' },
      { to: '/restaurant-desk/reservations', label: 'Table Reservations' },
      { to: '/restaurant-desk/orders', label: 'Orders & Kitchen' },
      { to: '/restaurant-desk/inventory', label: 'Inventory Overview' },
      { to: '/restaurant-desk/sales', label: 'Sales' },
      { to: '/restaurant-desk/reports', label: 'Reports' },
      { to: '/restaurant-desk/promotions', label: 'Promotions' },
      { to: '/restaurant-desk/feedback', label: 'Customer Feedback' },
    ],
  },
  events_manager: {
    path: '/events-desk',
    title: 'Events Manager',
    subtitle: 'Conference, wedding & private events',
    roles: ['events_manager'],
    links: [
      { to: '/events-desk', label: 'Overview', end: true },
      { to: '/events-desk/bookings', label: 'Event Bookings' },
      { to: '/events-desk/conference', label: 'Conference' },
      { to: '/events-desk/weddings', label: 'Weddings' },
      { to: '/events-desk/corporate', label: 'Corporate Events' },
      { to: '/events-desk/halls', label: 'Hall Management' },
      { to: '/events-desk/equipment', label: 'Equipment' },
      { to: '/events-desk/packages', label: 'Packages' },
      { to: '/events-desk/calendar', label: 'Calendar' },
      { to: '/events-desk/reports', label: 'Reports' },
    ],
  },
  service_ops: {
    path: '/ops',
    title: 'Service Operations',
    subtitle: 'Housekeeping & outside catering',
    roles: ['service_ops'],
    links: [
      { to: '/ops', label: 'Overview', end: true },
      { to: '/ops/cleaning', label: 'Cleaning Schedules' },
      { to: '/ops/inspection', label: 'Room Inspection' },
      { to: '/ops/laundry', label: 'Laundry' },
      { to: '/ops/maintenance', label: 'Maintenance' },
      { to: '/ops/lost-found', label: 'Lost & Found' },
      { to: '/ops/readiness', label: 'Room Readiness' },
      { to: '/ops/catering', label: 'Catering Requests' },
      { to: '/ops/quotations', label: 'Quotations' },
      { to: '/ops/staff', label: 'Staff & Vehicles' },
      { to: '/ops/reports', label: 'Reports' },
    ],
  },
  finance: {
    path: '/finance',
    title: 'Finance Office',
    subtitle: 'Payments, revenue & financial control',
    roles: ['finance'],
    links: [
      { to: '/finance', label: 'Overview', end: true },
      { to: '/finance/payments', label: 'Payments' },
      { to: '/finance/invoices', label: 'Invoices' },
      { to: '/finance/refunds', label: 'Refunds' },
      { to: '/finance/revenue', label: 'Revenue Breakdown' },
      { to: '/finance/expenses', label: 'Expenses & Taxes' },
      { to: '/finance/reports', label: 'Financial Reports' },
      { to: '/finance/export', label: 'Export Reports' },
    ],
  },
  admin: {
    path: '/admin',
    title: 'System Administrator',
    subtitle: 'Full hotel system control',
    roles: ['admin'],
    links: [
      { to: '/admin', label: 'Overview', end: true },
      { to: '/admin/users', label: 'User Management' },
      { to: '/admin/roles', label: 'Roles & Permissions' },
      { to: '/admin/rooms', label: 'Rooms' },
      { to: '/admin/bookings', label: 'Bookings' },
      { to: '/admin/restaurant', label: 'Restaurant' },
      { to: '/admin/events', label: 'Events' },
      { to: '/admin/catering', label: 'Outside Catering' },
      { to: '/admin/housekeeping', label: 'Housekeeping' },
      { to: '/admin/finance', label: 'Finance' },
      { to: '/admin/cms', label: 'CMS & Content' },
      { to: '/admin/gallery', label: 'Gallery & Media' },
      { to: '/admin/offers', label: 'Offers' },
      { to: '/admin/settings', label: 'Website Settings' },
      { to: '/admin/agent-requests', label: 'AI Agent Requests' },
      { to: '/admin/ai', label: 'AI Configuration' },
      { to: '/admin/reports', label: 'Analytics & Reports' },
      { to: '/admin/audit', label: 'Audit & Activity' },
      { to: '/admin/security', label: 'Security & 2FA' },
      { to: '/admin/system', label: 'System Health' },
      { to: '/admin/backups', label: 'Backups' },
    ],
  },
};

export function dashboardForRole(role) {
  return ROLE_DASHBOARDS[role] || ROLE_DASHBOARDS.customer;
}
